/* DOMAIN API */
//export const API = "http://shop-dev.teamcode.info";

export const API = "http://localhost:8080";

/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';


/*  ACCOUNT GROUP */
export const LIST_ACCOUNT = 'GET_LIST_ACCOUNT';
export const LIST_ACCOUNT_SC = 'GET_LIST_ACCOUNT_SC';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SC = 'DELETE_ACCOUNT_SC';
export const MODAL_OPEN = 'MODAL_OPEN_ADD';
export const MODAL_OPEN_SC = 'MODAL_OPEN_ADD_SC';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_ACCOUNT_SC = 'ADD_ACCOUNT_SC';
export const MODAL_EDIT = 'MODAL_EDIT';
export const MODAL_EDIT_SC = 'MODAL_EDIT_SC';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const CLOSE_MODAL_EDIT_ACCOUNTG = 'CLOSE_MODAL_ACCOUNTG';
export const CLOSE_MODAL_ADD_ACG = "CLOSE_MODAL_ADD_ACG";

/* ACCOUNT LIST */
export const OPEN_LOADING_ACCOUNTL = "OPEN_LOADING_ACCOUNTL";
export const LIST_ACCOUNTL = 'GET_LIST_ACCOUNTL';
export const LIST_ACCOUNT_SCL = 'GET_LIST_ACCOUNT_SCL';
export const DELETE_ACCOUNTL = 'DELETE_ACCOUNTL';
export const DELETE_ACCOUNT_SCL = 'DELETE_ACCOUNT_SCL';
export const MODAL_OPEN_ADD_ACCOUNTL = 'MODAL_OPEN_ADD_ACCOUNTL';
export const MODAL_OPEN_ADD_ACCOUNTL_SC = 'MODAL_OPEN_ADD_ACCOUNTL_SC';
export const ADD_ACCOUNTL = 'ADD_ACCOUNTL';
export const ADD_ACCOUNT_SCL = 'ADD_ACCOUNT_SCL';
export const MODAL_EDITL = 'MODAL_EDITL';
export const MODAL_EDIT_SCL = 'MODAL_EDIT_SCL';
export const UPDATE_ACCOUNTL = 'UPDATE_ACCOUNTL';
export const CLOSE_MODAL_EDIT_ACCOUNTL = 'CLOSE_MODAL_ACCOUNTL';
export const CLOSE_MODAL_ADD_ACL = "CLOSE_MODAL_ADD_ACL";


/*  PRODUCT */
export const LIST_PRODUCT = 'GET_LIST_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const MODAL_ADD_PRODUCT = 'MODAL_ADD_PRODUCT';
export const PRODUCT_SET_TYPE_LIST = 'PRODUCT_SET_TYPE_LIST';
export const UPLOAD_AVATAR_PRODUCT = 'UPLOAD_AVATAR_PRODUCT';
export const LOADING_DATA_PRODUCT = 'LOADING_DATA_PRODUCT';
export const GET_FILTER_OPTIONS = 'GET_FILTER_OPTIONS';
export const LIST_CATEGORY_HEADER_PRODUCT = "LIST_CATEGORY_HEADER_PRODUCT";
export const LIST_CATEGORY_HEADER_PRODUCT_SC = "LIST_CATEGORY_HEADER_PRODUCT_SC";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SC = "ADD_PRODUCT_SC";
export const MODAL_IMAGE_PRODUCT = 'MODAL_IMAGE_PRODUCT';
export const MODAL_IMAGE_PRODUCT_SC = 'MODAL_IMAGE_PRODUCT_SC';
export const UPLOAD_IMAGE_PRODUCT = 'UPLOAD_IMAGE_PRODUCT';
export const UPLOAD_IMAGE_PRODUCT_SC = 'UPLOAD_IMAGE_PRODUCT_SC';
export const REMOVE_IMAGE_PRODUCT = 'REMOVE_IMAGE_PRODUCT';
export const REMOVE_IMAGE_PRODUCT_SC = 'REMOVE_IMAGE_PRODUCT_SC';
export const GET_LIST_PRODUCT_HOME = 'GET_LIST_PRODUCT_HOME';
export const GET_LIST_PRODUCT_HOME_SC = 'GET_LIST_PRODUCT_HOME_SC';
export const GET_PRODUCT_HOME = 'GET_PRODUCT_HOME';
export const GET_PRODUCT_HOME_SC = 'GET_PRODUCT_HOME_SC';
/*  CATEGORY */
export const LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const LIST_CATEGORY_SC = 'GET_LIST_CATEGORY_SC';
export const LIST_CATEGORY_HEADER = 'GET_LIST_CATEGORY_HEADER';
export const MODAL_ADD_CATEGORY = 'MODAL_ADD_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

/*  CAROUSEL */
export const LIST_CAROUSEL = 'GET_LIST_CAROUSEL';
export const LIST_CAROUSEL_SC = 'GET_LIST_CAROUSEL_SC';
export const LIST_CAROUSEL_HEADER = 'GET_LIST_CAROUSEL_HEADER';
export const UPDATE_STATUS_CAROUSEL = 'UPDATE_STATUS_CAROUSEL';
export const ADD_CAROUSEL = 'ADD_CAROUSEL';
export const ADD_CAROUSEL_SC = 'ADD_CAROUSEL_SC';
export const MODAL_ADD_CAROUSEL = 'MODAL_ADD_CAROUSEL';
export const GET_LIST_SLIDER_HOME = 'GET_LIST_SLIDER_HOME';
export const GET_LIST_SLIDER_HOME_SC = 'GET_LIST_SLIDER_HOME_SC';
export const GET_LIST_CATEGORY_HOME = 'GET_LIST_CATEGORY_HOME';
export const GET_LIST_CATEGORY_HOME_SC = 'GET_LIST_CATEGORY_HOME_SC';


/* ROLES */
export const LIST_ROLE = 'GET_LIST_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const ADD_ROLE = 'ADD_ROLE';
export const ADD_ROLE_SC = 'ADD_ROLE_SUCCESS';
export const LIST_ROLE_SC = 'GET_LIST_ROLE_SUCCESS';
export const DELETE_ROLE_SC = 'DELETE_LIST_ROLE_SUCCESS';
export const MODAL_ADD_ROLE = 'MODAL_ADD_ROLE';


/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';


/* TODO APP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";


/* CHAT APP*/
export const CHAT_GET_CONTACTS= "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS= "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR= "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS= "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS= "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR= "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION= "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION= "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT= "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION= "CHAT_CHANGE_CONVERSATION";



/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER = "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER = "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE = "SURVEY_LIST_SELECTED_ITEMS_CHANGE";


/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";


/* LANDING PAGE */
export const LANDING_PAGE_MOBILE_MENU_TOGGLE = 'LANDING_PAGE_MOBILE_MENU_TOGGLE';
export const LANDING_PAGE_MOBILE_MENU_CLOSE = 'LANDING_PAGE_MOBILE_MENU_CLOSE';


